name: CI smoke test

on:
  pull_request:
  push:
    branches: ["main", "momentic-demo"]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MOMENTIC_API_KEY: ${{ secrets.MOMENTIC_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: npx momentic install-browsers --all

      - run: npx momentic run tests/cli-test-run.test.yaml --api-key $MOMENTIC_API_KEY
